<?php
use Bridge\Session;
use App\Utility\Identity\UserManager;
use App\Utility\Datetime\Timezone;
?>
<section id="table-user">

    <div class="page-header">
        <h1>User Information</h1>
    </div>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th style="width:150px">Topic</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Account</td>
                <td><?php echo $this->authUser->getAccount(); ?></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><?php echo $this->authUser->getEmail(); ?></td>
            </tr>
            <tr>
                <td>Roles</td>
                <td><?php echo join(", ", $this->authUser->getRoleDescriptions() ); ?></td>
            </tr>
            <tr>
                <td>Login Timeout</td>
                <td>
                    <p>
                        <b><?php echo Timezone::getSystem(); ?></b>
                    </p>
                    <p>
                        <?php echo date('H:i:s'); ?> (current)
                    </p>
                    <p>
                        <?php echo date('H:i:s', Session::get('session_expire')); ?> (expire)
                    </p>

                    <hr>

                    <p>
                        <b>Asia/Taipei</b>
                    </p>
                    <p>
                        <?php echo cc('convertTimezone', time(), 'Asia/Taipei', 'H:i:s'); ?> (current)
                    </p>
                    <p>
                        <?php echo cc('convertTimezone', Session::get('session_expire'), 'Asia/Taipei', 'H:i:s'); ?> (expire)
                    </p>
                </td>
            </tr>
        </tbody>
    </table>

</section>

<?php
    if (UserManager::isDebugMode()) {
        pr($_SESSION);
    }
