<form method="post">

    <div class="card">
        <div class="card-block">

            <div class="form-group">
                <label for="account">Your Account</label>
                <input type="text" class="form-control" name="account" value="<?php echo $this->authUser->getAccount(); ?>" disabled="disabled" />
            </div>

            <?php
                $item = cc('formMessageTheme', 'password');
                echo <<<"EOD"
                    <div class="form-group {$item->group}">
                        <label  for="password">* New Password</label>
                        <input name="password" type="password" class="form-control {$item->input}">
                        <span class="has-warning checkbox {$item->hidden}">{$item->message}</span>
                    </div>
EOD;

                $item = cc('formMessageTheme', 'password2');
                echo <<<"EOD"
                    <div class="form-group {$item->group}">
                        <label  for="password2">* Confirm New Password</label>
                        <input name="password2" type="password" class="form-control {$item->input}">
                        <span class="has-warning checkbox {$item->hidden}">{$item->message}</span>
                    </div>
EOD;

                $item = cc('formMessageTheme', 'oldPassword');
                echo <<<"EOD"
                    <div class="form-group {$item->group}">
                        <label  for="oldPassword">* Old Password</label>
                        <input name="oldPassword" type="password" class="form-control {$item->input}">
                        <span class="has-warning checkbox {$item->hidden}">{$item->message}</span>
                    </div>
EOD;
            ?>

            <button type="submit" class="btn btn-primary">Save</button>

        </div>
    </div>

    <div class="card">
        <div class="card-block">
            <p><b>密碼結構的建議</b></p>
            <ul>
                <li>密碼要很長, 以避免被暴力破解</li>
                <li>符合以上要點, 密碼包含英文, 數字, 符號</li>
                <li>符合以上要點, 每個月都修改一次密碼</li>
                <li>密碼可以是有意義, 可理解之文字</li>
                <li>Example: "I never think of the future. It comes soon enough. Albert Einstein, 1879"</li>
            </ul>
        </div>
    </div>

</form>
