<?php
use Bridge\Session;
use App\Utility\Identity\UserManager;
?>
<section id="table-user">

    <div class="page-header">
        <h1>User Information</h1>
    </div>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th style="width:150px">Topic</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Account</td>
                <td><?php echo $this->authUser->getAccount(); ?></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><?php echo $this->authUser->getEmail(); ?></td>
            </tr>
            <tr>
                <td>Roles</td>
                <td><?php echo join(", ", $this->authUser->getRoleDescriptions() ); ?></td>
            </tr>
            <tr>
                <td>Login Timeout</td>
                <td>
                    <p>
                        <?php echo date('H:i:s', Session::get('session_expire')); ?> (expire)
                    </p>
                    <p>
                        <?php echo date('H:i:s'); ?> (current)
                    </p>
                </td>
            </tr>
        </tbody>
    </table>

</section>

<?php
    if (UserManager::isDebugMode()) {
        pr($_SESSION);
    }
?>
