<?php if (!isset($accounts['uri'])): ?>

    <h1>Twilio test</h1>
    <hr/>

    <div class="form-group">
        <label>Error Information</label>
        <pre><?php print_r($accounts); ?></pre>
    </div>

<?php else: ?>

    <h1>Twilio test</h1>
    <hr/>

    <div class="form-group">
        <label>Uri</label>
        <input class="form-control" value="<?php echo $accounts['uri']; ?>" readonly>
    </div>

    <div class="form-group">
        <label>account count</label>
        <input class="form-control" value="<?php echo count($accounts['accounts']); ?>" readonly>
    </div>

<?php endif; ?>