<?php
    $baseUrl = url('');
?>

        <script src="<?php echo $baseUrl; ?>/assets/jquery/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.2/js/tether.js"></script>

        <link  href="<?php echo $baseUrl; ?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <script src="<?php echo $baseUrl; ?>/assets/bootstrap/js/bootstrap.min.js"></script>
