<?php
use App\Utility\Output\MenuManager as MenuManager;

$menuInfos      = MenuManager::getMenuInfos();
$focusMain      = MenuManager::getFocusMain();
$focusMainSubs  = MenuManager::getFocusMainSubs();
$focusSub       = MenuManager::getFocusSub();
?>
<!DOCTYPE html>
<html>
    <?php
        $baseUrl = url('');
    ?>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script src="<?php echo $baseUrl; ?>/assets/jquery/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.2/js/tether.js"></script>

        <link  href="<?php echo $baseUrl; ?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <script src="<?php echo $baseUrl; ?>/assets/bootstrap/js/bootstrap.min.js"></script>
    </head>
    <body>

        <nav class="navbar navbar-static-top navbar-dark bg-inverse">
            <a class="navbar-brand" href="javascript:void(0)"><?php echo conf('app.project.name');  ?></a>
            <ul class="nav navbar-nav pull-left">
            <?php
                foreach ($menuInfos as $item) {
                    $url    = $item['main']['link'];
                    $key    = $item['main']['key'];
                    $label  = $item['main']['label'];

                    $active = '';
                    if ($focusMain && $focusMain['key'] === $key) {
                        $active = 'active';
                    }
                    echo '<li class="nav-item '. $active .'"><a class="nav-link" href="'. $url .'">'. $label .'</a></li>';
                }
            ?>
            </ul>
        </nav>

        <?php
            /*
            //TODO: 讓 樣版可以互 call
            if ($focusMainSubs) {
                //$template = App\Utility\View\ViewHelper::get('_global.layout.adminMenuTwoColumn');
                //echo di('view')->render($template, []);
            }
            else {
                //
            }
            */
        ?>

        <div class="container-fluid" style="margin-top:20px;">
            <div class="row">
                <div class="col-sm-2">
                    <div class="list-group">
                    <?php
                        foreach ($focusMainSubs as $sub) {
                            $active = '';
                            if ($focusSub['key']===$sub['key']) {
                                $active = 'active';
                            }
                            echo '<a class="list-group-item '. $active .'" href="'. $sub['link'] .'" >'. $sub['label'] .' (未處理權限)</a>';
                        }
                    ?>
                    </div>
                </div>
                <div class="col-sm-10">
                    {{content}}
                </div>
            </div>
        </div>

    </body>
</html>