<?php
    use App\Utility\Output\MenuManager as MenuManager;
    use App\Utility\Identity\UserManager as UserManager;

    $menuInfos      = MenuManager::getMenuInfos();
    $focusMain      = MenuManager::getFocusMain();
    $focusMainSubs  = MenuManager::getFocusMainSubs();
    $focusSub       = MenuManager::getFocusSub();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        {{sect.admin.resourceLoad}}
    </head>
    <body>

        <nav class="navbar navbar-static-top navbar-dark bg-inverse">
            <a class="navbar-brand" href="javascript:void(0)"><?php echo cc('trainingIcon'); ?></a>
            <a class="navbar-brand" href="javascript:void(0)"><?php echo conf('app.project.name');  ?></a>
            <ul class="nav navbar-nav pull-left">

                <?php
                    foreach ($menuInfos as $item) {
                        $url    = $item['main']['link'];
                        $key    = $item['main']['key'];
                        $label  = $item['main']['label'];

                        $active = '';
                        if ($focusMain && $focusMain['key'] === $key) {
                            $active = 'active';
                        }
                        echo '<li class="nav-item '. $active .'"><a class="nav-link" href="'. $url .'">'. $label .'</a></li>';
                    }
                ?>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Setting</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-header">&laquo; User &raquo;</a>
                        <a class="dropdown-item" href="<?php echo url('/me'); ?>"><?php echo UserManager::getUser()->getUsername(); ?></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-header">&laquo; Status &raquo;</a>
                        <a class="dropdown-item" href="<?php echo homeUrl('/logout'); ?>">Logout</a>
                    </div>
                </li>

            </ul>


        </nav>

        <div class="container-fluid" style="margin-top:20px;">

            <?php echo cc('formMessage'); ?>

            <?php if ($focusMainSubs): ?>

                <div class="row">
                    <div class="col-sm-2">
                        <div class="list-group">
                        <?php
                            foreach ($focusMainSubs as $sub) {
                                $active = '';
                                if ($focusSub['key']===$sub['key']) {
                                    $active = 'active';
                                }
                                echo '<a class="list-group-item '. $active .'" href="'. $sub['link'] .'" >'. $sub['label'] .'</a>';
                            }
                        ?>
                        </div>
                    </div>
                    <div class="col-sm-10">
                        {{content}}
                    </div>
                </div>

            <?php else: ?>

                {{content}}

            <?php endif; ?>
        </div>

    </body>
</html>