<!DOCTYPE html>
<html>
    <?php
        $baseUrl = url('');
    ?>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script src="<?php echo $baseUrl; ?>/assets/jquery/jquery.min.js"></script>
        <link  href="<?php echo $baseUrl; ?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <script src="<?php echo $baseUrl; ?>/assets/bootstrap/js/bootstrap.min.js"></script>
    </head>
    <body>
        <section>
            <div class="navbar navbar-inverse navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="<?php echo $baseUrl; ?>/">Home</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <div style="margin:20px;">
            {{content}}
        </div>
    </body>
</html>